execution_engine: asyncio
logger:
  transports: [console, file]
  level: debug
  progress_display: true
  path_settings:
    path_pattern: "logs/mcp-agent-{unique_id}.jsonl"
    unique_id: "timestamp" # Options: "timestamp" or "session_id"
    timestamp_format: "%Y%m%d_%H%M%S"

mcp:
  servers:
    puppeteer:
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-puppeteer"]


# OpenAI configuration for mcp-agent framework
openai:
  # Use this for LM Studio or other OpenAI-compatible endpoints
  base_url: "http://localhost:1234/v1"
  default_model: "qwen/qwen3-coder-30b"
  # Secrets (API keys, etc.) are stored in an mcp_agent.secrets.yaml file which can be gitignored
